#!/usr/bin/env bash
# Runs once on container creation (and again on rebuild). Must be idempotent.
set -euo pipefail

WORKSPACE="${1:-$PWD}"

echo "==> System packages"
# build-essential : GCC, so CGO is on and the backend links the cgo SQLite driver.
# time            : GNU time, for measuring builds on this shared host.
# python3         : the base image ships only python3-minimal, which carries a PARTIAL
#                   stdlib -- 're' and 'io' import fine, 'json' does not. Nothing in
#                   Grafana's build needs Python, but ad-hoc scripts reach for it.
sudo apt-get update
sudo apt-get install -y --no-install-recommends build-essential time python3

echo "==> Yarn via corepack"
corepack enable
# Materialise the packageManager version from package.json now, so the first `yarn`
# call in a worktree does not stop to download it from repo.yarnpkg.com.
(cd "$WORKSPACE" && corepack install)

echo "==> Shared Yarn store for multi-worktree work"
# Several port agents work in parallel in worktrees under $WORKSPACE/.worktrees/.
# A full node_modules is ~2.4 GB, so N worktrees would cost N x that. hardlinks-global
# makes each worktree share one copy of every identical file.
#
# This goes in a user-level ~/.yarnrc.yml on purpose. The repo's own .yarnrc.yml is
# upstream's file; editing it would conflict on every merge-forward onto a newer tag.
# Yarn merges the two and the repo file sets neither globalFolder nor nmMode, so these
# apply without being overridden.
#
# globalFolder MUST live on the same filesystem as the worktrees. /home/vscode is the
# container overlay while $WORKSPACE is a bind mount, and hardlinks cannot cross a
# filesystem boundary -- left at its ~/.yarn/berry default, hardlinks-global silently
# degrades to plain copying and you get the N x cost back with no error.
GLOBAL_FOLDER="$WORKSPACE/.yarn-global"
mkdir -p "$GLOBAL_FOLDER"

cat > "$HOME/.yarnrc.yml" <<EOF
# Generated by .devcontainer/post-create.sh -- edit that script, not this file.
globalFolder: "$GLOBAL_FOLDER"
nmMode: hardlinks-global
EOF

# Verify the invariant rather than assuming it: same st_dev means hardlinks are possible.
if [ "$(stat -c %d "$GLOBAL_FOLDER")" != "$(stat -c %d "$WORKSPACE")" ]; then
  echo "WARNING: $GLOBAL_FOLDER and $WORKSPACE are on different filesystems." >&2
  echo "         hardlinks-global will fall back to copying and each worktree will cost a full node_modules." >&2
fi

# Keep the store untracked. info/exclude is in the common git dir, so this covers
# every worktree, and unlike .gitignore it is not a tracked file upstream will conflict on.
EXCLUDE="$WORKSPACE/.git/info/exclude"
for pat in '/.yarn-global/' '/.locks/'; do
  if [ -f "$EXCLUDE" ] && ! grep -qxF "$pat" "$EXCLUDE"; then
    echo "$pat" >> "$EXCLUDE"
  fi
done

echo "==> Done. Go module cache (/go/pkg/mod) and build cache (~/.cache/go-build) are"
echo "    already outside the worktrees, so all worktrees share them with no extra setup."
